apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookservice
  template:
    metadata:
      labels:
        app: bookservice
    spec:
      containers:
      - name: bookservice
        image: my-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: book-service-config
        - secretRef:
            name: postgres-secret
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bookservice
spec:
  type: ClusterIP
  selector:
    app: bookservice
  ports:
  - port: 80
    targetPort: 80
