apiVersion: v1
kind: ConfigMap
metadata:
  name: celery-worker-config
data:
  BROKER_URL: amqp://rabbitmq:5672
  RESULT_BACKEND: redis://my-redis-master:6379/0
  DATABASE_URL: postgresql+asyncpg://user:pass@my-postgresql:5432/bookdb
