apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-book-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-book-service
  template:
    metadata:
      labels:
        app: fastapi-book-service
    spec:
      containers:
      - name: fastapi-book-service
        image: fastapi-book-service:k8s
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: book-service-config
        - secretRef:
            name: postgres-secret
